exports.lang= [ ["python","file.py","","Python",""],
                   ["ruby","file.rb","","Ruby",""],
                   ["clojure","file.clj","","Clojure",""],
                   ["php","file.php","","Php",""],
                   ["nodejs","file.js","","Nodejs",""],
                   ["scala","file.scala","","Scala",""],
                   ["\'go run\'","file.go","","Go",""],
                   ["\'g++ -o /user/a.out\' ","file.cpp","/user/a.out","C/C++",""],
                   ["javac","file.java","\'./user/javaRunner.sh\'","Java",""],
                   ["\'vbnc -nologo -quiet\'","file.vb","\'mono /user/file.exe\'","VB.Net",""],
                   ["gmcs","file.cs","\'mono /user/file.exe\'","C#",""],
                   ["/bin/bash","file.sh"," ","Bash",""],
                   ["gcc ","file.m"," /user/a.out","Objective-C","\' -o /user/a.out -I/usr/include/GNUstep -L/usr/lib/GNUstep -lobjc -lgnustep-base -Wall -fconstant-string-class=NSConstantString\'"],
                   ["/user/sql_runner.sh","file.sql","","MYSQL",""],
                   ["perl","file.pl","","Perl",""],
                   ["\'env HOME=/opt/rust /opt/rust/.cargo/bin/rustc\'","file.rs","/user/a.out","Rust","\'-o /user/a.out\'"] ];
